name: test suite

on:
  push:
    branches: [master]
  pull_request:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.7", "3.10", "3.11", "3.12", "pypy-3.10"]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        allow-prereleases: true
        cache: pip
        cache-dependency-path: pyproject.toml
    - name: Start external services
      run: docker-compose up -d
    - name: Install dependencies
      run: pip install .[test]
    - name: Test with pytest
      run: coverage run -m pytest -v
    - name: Generate coverage report
      run: coverage xml
    - name: Upload Coverage
      uses: coverallsapp/github-action@v2
      with:
        parallel: true
        file: coverage.xml

  coveralls:
    name: Finish Coveralls
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Finished
      uses: coverallsapp/github-action@v2
      with:
        parallel-finished: true
